public class BikeRunner{
	public static void main(String args[]){
	Bike bike = new Bike();
	System.out.println("The bike name is:"+bike.BikeName);
	System.out.println("The bike gives :"+bike.milage);
	System.out.println("The bike ratings is:"+bike.rating);
	System.out.println("The bike cost is:"+bike.price);
	System.out.println("The bike is of:"+bike.electric);
	System.out.println("The bike has:"+bike.gears);
	System.out.println("The bikelicen is:"+bike.license);
	System.out.println("The bike storage is:"+bike.capacity);
	System.out.println("The bikeroute is:"+bike.route);
	System.out.println("The biketypes is:"+bike.abs);
	System.out.println("The bikeheight is:"+bike.height);
	System.out.println("The bikecolor is:"+bike.color);
	System.out.println("The bikeleng is:"+bike.length);
	System.out.println("The bike is of:"+bike.fuel);
	System.out.println("The bikeno is:"+bike.serialno);
	System.out.println("The biketype is:"+bike.type);
	System.out.println("The bike can hold persons:"+bike.persons);
	Bike bike1 = new Bike();
	System.out.println("The bike name is:"+bike1.BikeName);
	System.out.println("The bike gives :"+bike1.milage);
	System.out.println("The bike ratings is:"+bike1.rating);
	System.out.println("The bike cost is:"+bike1.price);
	System.out.println("The bike is of:"+bike1.electric);
	System.out.println("The bike has:"+bike1.gears);
	System.out.println("The bikelicen is:"+bike1.license);
	System.out.println("The bike storage is:"+bike1.capacity);
	System.out.println("The bikeroute is:"+bike1.route);
	System.out.println("The biketypes is:"+bike1.abs);
	System.out.println("The bikeheight is:"+bike1.height);
	System.out.println("The bikecolor is:"+bike1.color);
	System.out.println("The bikeleng is:"+bike1.length);
	System.out.println("The bike is of:"+bike1.fuel);
	System.out.println("The bikeno is:"+bike1.serialno);
	System.out.println("The biketype is:"+bike1.type);
	System.out.println("The bike can hold persons:"+bike1.persons);
	Bike bike2 = new Bike();
	System.out.println("The bike name is:"+bike2.BikeName);
	System.out.println("The bike gives :"+bike2.milage);
	System.out.println("The bike ratings is:"+bike2.rating);
	System.out.println("The bike cost is:"+bike2.price);
	System.out.println("The bike is of:"+bike2.electric);
	System.out.println("The bike has:"+bike2.gears);
	System.out.println("The bikelicen is:"+bike2.license);
	System.out.println("The bike storage is:"+bike2.capacity);
	System.out.println("The bikeroute is:"+bike2.route);
	System.out.println("The biketypes is:"+bike2.abs);
	System.out.println("The bikeheight is:"+bike2.height);
	System.out.println("The bikecolor is:"+bike2.color);
	System.out.println("The bikeleng is:"+bike2.length);
	System.out.println("The bike is of:"+bike2.fuel);
	System.out.println("The bikeno is:"+bike2.serialno);
	System.out.println("The biketype is:"+bike2.type);
	System.out.println("The bike can hold persons:"+bike2.persons);
	Bike bike3 = new Bike();
	System.out.println("The bike name is:"+bike3.BikeName);
	System.out.println("The bike gives :"+bike3.milage);
	System.out.println("The bike ratings is:"+bike3.rating);
	System.out.println("The bike cost is:"+bike3.price);
	System.out.println("The bike is of:"+bike3.electric);
	System.out.println("The bike has:"+bike3.gears);
	System.out.println("The bikelicen is:"+bike3.license);
	System.out.println("The bike storage is:"+bike3.capacity);
	System.out.println("The bikeroute is:"+bike3.route);
	System.out.println("The biketypes is:"+bike3.abs);
	System.out.println("The bikeheight is:"+bike3.height);
	System.out.println("The bikecolor is:"+bike3.color);
	System.out.println("The bikeleng is:"+bike3.length);
	System.out.println("The bike is of:"+bike3.fuel);
	System.out.println("The bikeno is:"+bike3.serialno);
	System.out.println("The biketype is:"+bike3.type);
	System.out.println("The bike can hold persons:"+bike3.persons);
	
	
	}
	}