public class BusRunner{
	public static void main(String args[]){
	Bus bus = new Bus();
	System.out.println("The bus name is:"+bus.BusName);
	System.out.println("The bus charge:"+bus.ticket);
	System.out.println("The bus ratings is:"+bus.rating);
	System.out.println("The bus cost is:"+bus.price);
	System.out.println("The bus is of:"+bus.electric);
	System.out.println("The busdoor is:"+bus.doors);
	System.out.println("The buslicen is:"+bus.license);
	System.out.println("The bus storage is:"+bus.capacity);
	System.out.println("The busroute is:"+bus.route);
	System.out.println("The bustypes is:"+bus.doubledecker);
	System.out.println("The bussoze is:"+bus.height);
	System.out.println("The buscolor is:"+bus.color);
	System.out.println("The busleng is:"+bus.length);
	System.out.println("The bus is:"+bus.fuel);
	System.out.println("The busno is:"+bus.serialno);
	System.out.println("The bustype is:"+bus.type);
	System.out.println("The bus persons is:"+bus.persons);
	Bus bus1 = new Bus();
	System.out.println("The bus name is:"+bus1.BusName);
	System.out.println("The bus charge:"+bus1.ticket);
	System.out.println("The bus ratings is:"+bus1.rating);
	System.out.println("The bus cost is:"+bus1.price);
	System.out.println("The bus is of:"+bus1.electric);
	System.out.println("The busdoor is:"+bus1.doors);
	System.out.println("The buslicen is:"+bus1.license);
	System.out.println("The bus storage is:"+bus1.capacity);
	System.out.println("The busroute is:"+bus1.route);
	System.out.println("The bustypes is:"+bus1.doubledecker);
	System.out.println("The bussoze is:"+bus1.height);
	System.out.println("The buscolor is:"+bus1.color);
	System.out.println("The busleng is:"+bus1.length);
	System.out.println("The bus is:"+bus1.fuel);
	System.out.println("The busno is:"+bus1.serialno);
	System.out.println("The bustype is:"+bus1.type);
	System.out.println("The bus persons is:"+bus1.persons);
	Bus bus2 = new Bus();
	System.out.println("The bus name is:"+bus2.BusName);
	System.out.println("The bus charge:"+bus2.ticket);
	System.out.println("The bus ratings is:"+bus2.rating);
	System.out.println("The bus cost is:"+bus2.price);
	System.out.println("The bus is of:"+bus2.electric);
	System.out.println("The busdoor is:"+bus.doors);
	System.out.println("The buslicen is:"+bus2.license);
	System.out.println("The bus storage is:"+bus2.capacity);
	System.out.println("The busroute is:"+bus2.route);
	System.out.println("The bustypes is:"+bus2.doubledecker);
	System.out.println("The bussoze is:"+bus2.height);
	System.out.println("The buscolor is:"+bus2.color);
	System.out.println("The busleng is:"+bus2.length);
	System.out.println("The bus is:"+bus2.fuel);
	System.out.println("The busno is:"+bus2.serialno);
	System.out.println("The bustype is:"+bus2.type);
	System.out.println("The bus persons is:"+bus2.persons);
	Bus bus3 = new Bus();
	System.out.println("The bus name is:"+bus3.BusName);
	System.out.println("The bus charge:"+bus3.ticket);
	System.out.println("The bus ratings is:"+bus3.rating);
	System.out.println("The bus cost is:"+bus3.price);
	System.out.println("The bus is of:"+bus3.electric);
	System.out.println("The busdoor is:"+bus3.doors);
	System.out.println("The buslicen is:"+bus3.license);
	System.out.println("The bus storage is:"+bus3.capacity);
	System.out.println("The busroute is:"+bus3.route);
	System.out.println("The bustypes is:"+bus3.doubledecker);
	System.out.println("The bussoze is:"+bus3.height);
	System.out.println("The buscolor is:"+bus3.color);
	System.out.println("The busleng is:"+bus3.length);
	System.out.println("The bus is:"+bus3.fuel);
	System.out.println("The busno is:"+bus3.serialno);
	System.out.println("The bustype is:"+bus3.type);
	System.out.println("The bus persons is:"+bus3.persons);
	}
	}